<a href="https://colab.research.google.com/github/Abhinay-880/Band-Name-Generator/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [ ]:
import numpy as np

In [ ]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [3]:
print(len(dir(np)))

532


In [4]:
arr = np.array([1,2,3,4,5]) #Creating a Array
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.ndim #Checking the Dimentions

1

In [10]:
np.array([[1,2],[2,1]]).ndim


2

In [11]:
np.array([[[[]]]]).shape #no. of rows,no. of columns ....

(1, 1, 1, 0)

In [12]:
arr = np.arange(10) #Range
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(1,2,5)  #linspace => evenly spread the range

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
np.logspace(1,2,5)  # it take powers of 10 in start,end , numbers we want

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [15]:
np.zeros(5) # it will create an array with zeros

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones(10) # it will create an array with ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones([1,2],dtype=int) # we can also specify data type ,it is optional

array([[1, 1]])

In [20]:
np.full(10,2) # we can create an array with a number with specific number of times

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
np.full([2,4],10) # [row,column] ,value

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [22]:
np.empty([2,2]) #create an empty array,it shows zero but it is empty

array([[0., 0.],
       [0., 0.]])